language: cpp
compiler:
    - gcc
    #- clang
branches:
  except:
    - master
notifications:
  email:
    - ryp.sqrt@gmail.com
before_install:
    - sudo add-apt-repository -y "deb http://fr.archive.ubuntu.com/ubuntu/ trusty main universe" # NOTE use ubuntu trusty repo instead of hacking with custom user packages
    - sudo apt-get update -qq
install:
    - sudo apt-get install -qq g++ clang cmake
    - sudo apt-get install -qq valgrind cppcheck
    - sudo apt-get install -qq libXxf86vm-dev
    - git clone https://github.com/glfw/glfw.git
    - pushd glfw
    - git checkout 3.0.4
    - cmake -DBUILD_SHARED_LIBS=ON . && make && sudo make install
    - popd
    - git clone https://github.com/hpicgs/glbinding.git
    - pushd glbinding
    - git checkout v1.0.3
    - cmake -DBUILD_SHARED_LIBS=ON . && make && sudo make install
    - popd
before_script:
    - mkdir build && pushd build
script:
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DMOGL_BUILD_TESTS=ON -DCMAKE_INSTALL_PREFIX=/usr
    - make
after_success:
    - ctest --output-on-failure
    - sudo make install
    - cppcheck ../mogl -q --force --enable=all
