language: cpp
compiler:
    - gcc
    - clang
branches:
  except:
    - master
notifications:
  email:
    - ryp.sqrt@gmail.com
before_install:
    - sudo add-apt-repository -y "deb http://fr.archive.ubuntu.com/ubuntu/ trusty main universe" # NOTE use ubuntu trusty repo instead of hacking with custom user packages
    - sudo apt-get update -qq
install:
    - sudo apt-get install -qq g++ clang cmake
    - sudo apt-get install -qq libglew-dev libglfw3-dev
    - sudo apt-get install -qq valgrind
before_script:
    - mkdir build && pushd build
script:
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DMOGL_BUILD_TESTS=ON -DCMAKE_INSTALL_PREFIX=/usr
    - make
after_success:
    - ctest --verbose
    - sudo make install
    - valgrind --leak-check=full --show-reachable=yes
