language: cpp
compiler:
    - gcc
    #- clang
branches:
  except:
    - gh-pages
notifications:
  email:
    - ryp.sqrt@gmail.com
env:
  global:
    - secure: "JVSODHpfFYesFxNQ/3jtl0pzO0MBnqyhL6GkFOYK3kNgfkNbN3m7iC9tl3gfS2etrpBSCUErwk8TGVa1yBvYY1uAea6mqWGqwQwKXkXpYn3nW8woouooQeplKYuSWeeKw2QSMUlgPEIePyQDh1JPyeYnB/nKi1V6PtbIscr5byE="
before_install:
    - sudo apt-get install -qq doxygen
    - sudo apt-get install -qq graphviz
    - sudo add-apt-repository -y "deb http://fr.archive.ubuntu.com/ubuntu/ utopic main universe" # NOTE use ubuntu utopic repo instead of hacking with custom user packages
    - sudo apt-get update -qq
install:
    - sudo apt-get install -qq g++ clang
    - sudo apt-get install -qq valgrind cppcheck libgtest-dev
    - sudo apt-get install -qq libXxf86vm-dev
    # gtest install
    - pushd /usr/src/gtest
    - sudo cmake . && sudo make && sudo mv libgtest* /usr/lib/
    - popd
    # cmake 3.2.1 install
    - wget http://www.cmake.org/files/v3.2/cmake-3.2.1-Linux-i386.tar.gz
    - tar -xzf cmake-3.2.1-Linux-i386.tar.gz
    - sudo cp -fR cmake-3.2.1-Linux-i386/* /usr
    - git clone -b 3.1 --single-branch https://github.com/glfw/glfw.git
    - pushd glfw
    - cmake -DBUILD_SHARED_LIBS=ON . && make -j2 && sudo make install
    - popd
    - git clone -b master --single-branch https://github.com/hpicgs/glbinding.git
    - pushd glbinding
    - cmake -DOPTION_BUILD_STATIC=OFF . && make -j2 && sudo make install
    - popd
before_script:
    - mkdir build && pushd build
script:
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DMOGL_BUILD_TESTS=ON -DCMAKE_INSTALL_PREFIX=/usr
    - make
after_success:
    - ctest --output-on-failure
    - sudo make install
    - popd
    - cppcheck -q --force --enable=warning --enable=style mogl test example
    # Push documentation on gh-pages branch
    - echo "PROJECT_NUMBER         = $TRAVIS_BRANCH" >> Doxyfile
    - doxygen
    - pushd $HOME
    - git config --global user.email "travis@travis-ci.org"
    - git config --global user.name "travis-ci"
    - git clone -b gh-pages --single-branch https://${GH_TOKEN}@github.com/Ryp/moGL gh-pages
    - pushd gh-pages
    - git rm -rf *
    - cp -r $TRAVIS_BUILD_DIR/html/* .
    - git reset --hard `git rev-list --max-parents=0 HEAD`
    - git add -f .
    - git commit --amend -am "Deploy to Github Pages"
    - git push -fq origin gh-pages
    - popd
    - popd
